[package]
name = "huffman"
version = "0.1.0"
authors = ["Caleb Sander"]
edition = "2018"

[lib]
path = "src/huffman.rs"

[dependencies]
priority_queue = { path = "../priority_queue" }
bit_vector = { path = "../bit_vector" }